[package]
name = "solana-short-vec"
description = "Solana compact serde-encoding of vectors with small length."
documentation = "https://docs.rs/solana-short-vec"
version = "3.2.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["serde"]
serde = ["dep:serde_core"]
frozen-abi = []

[dependencies]
serde_core = { workspace = true, optional = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
serde_json = { workspace = true }
solana-short-vec = { path = ".", features = ["serde"] }

[lints]
workspace = true
