//! This module extends `frozen-abi` with binary-level compatibility checks.
//! The StableAbi` ensures that the actual serialized byte representation remains consistent.

use {
    arbitrary::{Arbitrary, Unstructured},
    rand::RngCore,
};

/// Enables binary layout stability testing.
///
/// This trait is used to detect unintended changes in serialized representations.
/// Types that implement this trait can be tested via `test_abi_digest` (generated by
/// the `#[frozen_abi(abi_digest = "...")]` attribute), which creates deterministically
/// generated instances, hashes their binary representation, and compares the result
/// against the specified abi_digest.
///
/// Meant to be used with `#[derive(StableAbi)]` from `frozen-abi-macro`.
pub trait StableAbi: Sized {
    fn random(rng: &mut impl RngCore) -> Self
    where
        Self: for<'a> Arbitrary<'a>,
    {
        // NOTE: As bytes being consumed, it might lead to buffer exhaust.
        // In such case increase the `MAX_TYPE_SIZE` accordingly
        // keeping in mind that increasing this value has impact on frozen-abi tests runtime.
        const MAX_TYPE_SIZE: usize = 4096;

        let mut buffer = vec![0u8; MAX_TYPE_SIZE];
        rng.fill_bytes(&mut buffer);
        let mut unstructured = Unstructured::new(&buffer);

        Self::arbitrary(&mut unstructured).expect("failed to fill - try increasing MAX_TYPE_SIZE")
    }
}

#[cfg(test)]
mod tests {
    use {
        arbitrary::Arbitrary,
        frozen_abi_macro::{frozen_abi, AbiEnumVisitor, AbiExample, StableAbi},
        serde::{Deserialize, Serialize},
    };

    #[derive(
        Debug,
        Clone,
        PartialEq,
        Serialize,
        Deserialize,
        AbiExample,
        AbiEnumVisitor,
        StableAbi,
        Arbitrary,
    )]
    #[frozen_abi(api_digest = "PLACEHOLDER_API_1", abi_digest = "PLACEHOLDER_ABI_1")]
    pub struct AStruct {
        pub a: u64,
        pub b: i32,
        pub c: bool,
        pub d: Option<u32>,
        pub e: Option<String>,
        pub f: Vec<u8>,
        pub g: Vec<u64>,
        pub h: String,
    }

    #[derive(
        Debug,
        Clone,
        PartialEq,
        Serialize,
        Deserialize,
        AbiExample,
        AbiEnumVisitor,
        StableAbi,
        Arbitrary,
    )]
    #[frozen_abi(api_digest = "PLACEHOLDER_API_5", abi_digest = "PLACEHOLDER_ABI_5")]
    pub struct AOuterStruct {
        pub a: u64,
        pub b: AStruct,
        pub c: Vec<AStruct>,
    }

    #[derive(
        Debug,
        Clone,
        PartialEq,
        Serialize,
        Deserialize,
        AbiExample,
        AbiEnumVisitor,
        StableAbi,
        Arbitrary,
    )]
    #[frozen_abi(api_digest = "PLACEHOLDER_API_6", abi_digest = "PLACEHOLDER_ABI_6")]
    pub struct ATuple(pub u64, pub String, pub bool);

    #[derive(
        Debug,
        Clone,
        PartialEq,
        Serialize,
        Deserialize,
        AbiExample,
        AbiEnumVisitor,
        StableAbi,
        Arbitrary,
    )]
    #[frozen_abi(api_digest = "PLACEHOLDER_API_7", abi_digest = "PLACEHOLDER_ABI_7")]
    pub enum Enum {
        A,
        B,
        C,
    }
}
